language: java

script: travis_wait 120 ./.travis-build.sh

sudo: false

jdk:
  - oraclejdk8
#  - oraclejdk7
#  - openjdk7

## Temporarily disable, until the job is passing.
# notifications:
#   email:
#     - checker-framework-dev@googlegroups.com 
